// Refreshes the catalogue bundled into the app from the published one.
//
//   dart run tool/refresh_bundled_catalogue.dart            # fetch and replace
//   dart run tool/refresh_bundled_catalogue.dart path.csv   # from a local copy
//
// The bundled asset is what a fresh install shows before it has downloaded
// anything - at a launch site with no signal, it may be all a pilot ever sees.
// It is not generated by any build step, so it only moves when someone runs
// this, and it had drifted a long way: 11,690 rows against the published
// 18,761, no DHV at all, and none of the `site_type`, `site_group` or `notes`
// columns the app now reads. Every landing was missing, and so was every German
// and Swiss launch that PGE does not carry.
//
// Run it before a release, and whenever the producer adds a column.

import 'dart:convert';
import 'dart:io';

import 'package:csv/csv.dart';

const String catalogUrl = 'https://raw.githubusercontent.com/Kevin-McIsaac/'
    'paragliding_site_federation/main/app/sites.csv';

const String assetPath = 'assets/data/world_sites_extracted.csv.gz';

/// The columns the app's parser reads. A refresh that dropped one would leave
/// a fresh install worse off than before it ran.
const List<String> required = [
  'ref',
  'name',
  'longitude',
  'latitude',
  'altitude',
  'source',
  'site_type',
  'site_group',
];

Future<String> _load(List<String> args) async {
  if (args.isNotEmpty) return File(args.first).readAsStringSync();

  stderr.writeln('Fetching $catalogUrl');
  final client = HttpClient();
  try {
    final response = await (await client.getUrl(Uri.parse(catalogUrl))).close();
    if (response.statusCode != 200) {
      throw StateError('catalogue fetch failed: HTTP ${response.statusCode}');
    }
    return response.transform(utf8.decoder).join();
  } finally {
    client.close();
  }
}

void main(List<String> args) async {
  final published = await _load(args);
  final rows = csv.decodeWithHeaders(published);

  // Checked before anything is overwritten. A truncated download parses to a
  // handful of rows perfectly happily, and the failure would not show up until
  // a pilot opened the map on a fresh install.
  if (rows.length < 11000) {
    throw StateError('only ${rows.length} rows - refusing to ship that');
  }
  final headers = rows.first.headerMap.keys.toSet();
  final missing = required.toSet().difference(headers);
  if (missing.isNotEmpty) {
    throw StateError('published catalogue is missing $missing');
  }

  final asset = File(assetPath);
  final before = asset.existsSync() ? asset.lengthSync() : 0;
  asset.writeAsBytesSync(gzip.encode(utf8.encode(published)));

  stderr.writeln('Wrote ${rows.length} rows to $assetPath '
      '(${before ~/ 1024} KB -> ${asset.lengthSync() ~/ 1024} KB)');
}
